export const apiCallIds = {
    CREATE_WALLET: 'CREATE_WALLET',
    SEND_TRANSACTION: 'SEND_TRANSACTION',
    GENERATE_ADDRESS: 'GENERATE_ADDRESS',
    GET_BALANCE: 'GET_BALANCE',
    GET_ADDRESSES: 'GET_ADDRESSES',
    GET_TX_HISTORY: 'GET_TX_HISTORY',
    EXPORT_WALLET: 'EXPORT_WALLET',
    IMPORT_WALLET: 'IMPORT_WALLET',
};
